## Basics Exercise

In [1]:
import numpy as np

#### NumPy array creation

In [4]:
# create a numpy array using the python list
list = [1,2,3,4,5]
print(type(list))

np_array = np.array(list)   # object of ndarray class
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
# create a random numpy array

random_np_array = np.random.randint(0,3,size=6)
# 0 is inclusive and 3 is exclusive
print(random_np_array)

[1 1 2 2 2 0]


In [8]:
a1 = np.random.rand(5)
a1

array([0.35564572, 0.15715532, 0.76041474, 0.39209563, 0.25701629])

In [12]:
# creating an empty array and array of zeros and ones

empty_array = np.empty(5)
print(empty_array)   # the values it print are the values which are already present in the allocated memory

one_array = np.ones(4, dtype='int')
print(one_array)

zero_array = np.zeros(4)
print(zero_array)

[0.35564572 0.15715532 0.76041474 0.39209563 0.25701629]
[1 1 1 1]
[0. 0. 0. 0.]


In [16]:
# numpy array using arrange function
# arrange(start=0, end, step=1, dtype)
range_array = np.arange(10)
print(range_array)

range_array_2 = np.arange(2,10,2,dtype='float')
print(range_array_2)

[0 1 2 3 4 5 6 7 8 9]
[2. 4. 6. 8.]


#### Integer, Float, Boolean, Complex data type in array

In [17]:
# array_1 = np.array([200,200,300] dtype=np.int8)   // this will through array 
array_1  = np.array([200,200,300], dtype=np.int16)
print(array_1)

[200 200 300]


In [19]:
array_2 = np.array([1.2,3.2,4.5],dtype=np.float16)
print(array_2)

[1.2 3.2 4.5]


In [21]:
#### Boolean data type in numpy
arr_bool = np.array([True, False, True], dtype=np.bool_)
print(arr_bool)

arr_bool_1 = np.array([0,0,1], dtype=np.bool_)
print(arr_bool_1)

arr_bool_2 = np.array([True, False])
print(arr_bool_2)

[ True False  True]
[False False  True]
[ True False]


#### string and object dataype in np array

In [22]:
arr_str = np.array(['ummed','choudhary'],dtype='str')
print(arr_str)

['ummed' 'choudhary']


In [29]:
arr_object = np.array([1,'1',1.1],dtype=object)
print(arr_object.dtype)

object


#### Basic array attribute

In [31]:
a1 = np.array([1,2,3],dtype='int8')
print(a1.size)
print(a1.dtype)
print(a1.itemsize)   # returns the size (in bytes) of each elements in the array

3
int8
1


#### Array Indexing in numpy

In [41]:
# Boolean Indexing : values are faetching or filtering based on values or some cinditions rather then the index value

arr_b = np.arange(10)
print(arr_b)

mask = arr_b > 5
print(mask)

filtered_array = arr_b[mask]
print(filtered_array)

arr_even = arr_b[arr_b%2 == 0]
print(arr_even)

arr_b[arr_b%2 == 1] = -1     # chnage the specific values of an array
print(arr_b)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[0 2 4 6 8]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### N-dimentional array

In [46]:
# take an example of an image of 3*3 pixel
# each pixel is an array of three number which represent the color of pixel

image = np.array([[[225,0,0],[0,225,0],[0,0,225]],
         [[225,225,0],[0,225,225],[225,0,225]],
         [[0,0,0],[225,225,225],[123,222,123]]])

# here each pixel represent different color

print(image.size)
print(image.shape)
print(image.dtype)

27
(3, 3, 3)
int32


In [64]:
# generate n-d array
arr = np.zeros((3,3),dtype='int')
print(arr)
arr2 = np.ones((3,2,3),dtype=int)
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [67]:
# generate and re-shape the array
ary_1 = np.arange(12)
ary_1 = ary_1.reshape(3,4)
print(ary_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [69]:
# let's create an array of shape = (2,3,4)
ary_2 = np.arange(24)
ary_2 = ary_2.reshape(2,3,4)
ary_2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [72]:
# indexing the n-d array

# 5,6,7
# 9,10,11
# 17,18,19
# 21,22,23
sub_array = ary_2[:,1:,1:]
sub_array

array([[[ 5,  6,  7],
        [ 9, 10, 11]],

       [[17, 18, 19],
        [21, 22, 23]]])

#### Arithmetic operation on NumPy arrays

In [3]:
# element-wise arithmetic operation

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(arr_1+arr_2)
print(arr_2 // arr_1)

[5 7 9]
[4 2 2]


In [4]:
# scaler operation envolve performing arithmetic operation on array using sinle value

print(arr_1 + 10)
print(arr_2 * 10)

[11 12 13]
[40 50 60]


In [8]:
# built-in function for arithmetic operation

arr_1 = np.array([1,2,3,4])
print(np.sum(arr_1))
print(np.prod(arr_1))
print(np.cumsum(arr_1))
print(np.cumprod(arr_1))

print(np.add(arr_1,arr_1))
print(np.divide(arr_1,arr_1))

10
24
[ 1  3  6 10]
[ 1  2  6 24]
[2 4 6 8]
[1. 1. 1. 1.]


#### comparison operator in Numpy

In [9]:
# we can compare two arrays using <,>,<=,>=,==,!= and the result is boolean array

a1 = np.array([1,3,5,2,0])
a2 = np.array([2,3,4,6,1])

print(a1>a2)
print(a1>=a2)

print(a1 == a2)
print(a1!=a2)

[False False  True False False]
[False  True  True False False]
[False  True False False False]
[ True False  True  True  True]


In [13]:
 # we have logical function as well which is work on boolean array

a3 = np.array([1,0,0,1],dtype='bool')
a4 = np.array([0,1,0,1], dtype='bool')

print(np.logical_and(a3,a4))
print(np.logical_or(a3,a4))
print(np.logical_not(a3))
print(np.logical_xor(a3,a4))

[False False False  True]
[ True  True False  True]
[False  True  True False]
[ True  True False False]


In [42]:
matrix = np.array([
    [1, 12, 15],
    [8, 23, 4],
    [9, 6, 17]
])
threshold = 10
a = (matrix%2 == 0) & (matrix>10)
print(a*matrix)

[[ 0 12  0]
 [ 0  0  0]
 [ 0  0  0]]


#### working with string in NumPy

In [3]:
# arithmetic operation
a = np.array(['hello','good'])
b = np.array(['world','morning'])

print(np.char.add(a,b))
print(np.char.capitalize(a))
print(np.char.multiply(a,2))

['helloworld' 'goodmorning']
['Hello' 'Good']
['hellohello' 'goodgood']


In [4]:
# case conversion
print(np.char.lower(a))
print(np.char.upper(b))

['hello' 'good']
['WORLD' 'MORNING']


In [5]:
# splitting of string
ab = np.array([['hello world','good morning'],['hello namaskar','happy coding']])
a_b = np.char.split(ab)   # output : array of list
print(ab)
print(a_b)

[['hello world' 'good morning']
 ['hello namaskar' 'happy coding']]
[[list(['hello', 'world']) list(['good', 'morning'])]
 [list(['hello', 'namaskar']) list(['happy', 'coding'])]]


In [6]:
print(np.char.join('-',ab))

[['h-e-l-l-o- -w-o-r-l-d' 'g-o-o-d- -m-o-r-n-i-n-g']
 ['h-e-l-l-o- -n-a-m-a-s-k-a-r' 'h-a-p-p-y- -c-o-d-i-n-g']]


In [12]:
# string searching
a = np.array(['ummed','choudhary'])
print(np.char.find(a,'h'))
print(np.char.rfind(a,'h'))
print(np.char.find(a,'mm'))

[-1  1]
[-1  5]
[ 1 -1]


In [13]:
# string modification
# removing white space

a = np.array(['   ummed ',' suki  ',' h ','rohit  '])
print(np.char.lstrip(a)) # remove leading white space
print(np.char.rstrip(a)) # remove white space from the end
print(np.char.strip(a)) # remove leading and ending white space

['ummed ' 'suki  ' 'h ' 'rohit  ']
['   ummed' ' suki' ' h' 'rohit']
['ummed' 'suki' 'h' 'rohit']


In [14]:
# replace string

b = ['aaa','bbb','aaa ',' bbb  ']
print(np.char.replace(b,'a','x'))

['xxx' 'bbb' 'xxx ' ' bbb  ']


In [15]:
print(np.char.replace(b,' ',''))   # removing all the white space

['aaa' 'bbb' 'aaa' 'bbb']


In [20]:
# validation string
data = np.array([
    ['Alice', '25'],
    ['Bob123', '30'],
    ['Charlie', 'Twenty'],
    ['Diana', '40'],
    ['Eve', '32years']
])

name_valid = np.char.isalpha(data[:,0])
age_valid = np.char.isdigit(data[:,1])
result = np.column_stack((name_valid, age_valid))
print(result)

[[ True  True]
 [False  True]
 [ True False]
 [ True  True]
 [ True False]]
